tasker/lists/api/urls.py
from django.urls import path, include
from rest_framework import routers
from . import views

router = routers.DefaultRouter()
router.register('lists', views.ListViewSet)
router.register('tasks', views.TaskViewSet)



app_name = 'lists'

urlpatterns = [
    path('', include(router.urls)),
]

tasker/lists/urls.py
from django.urls import path

from . import views

app_name = 'lists'
urlpatterns = [
    path('', views.home, name='home'),
    path('list/<list_id>/', views.list_detail, name='detail'),
]

tasker/tasker/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("api/", include('lists.api.urls', namespace='lists')),

]

tasker/user/urls.py
from django.urls import path
from .views import CreateUserView, CreateTokenView, ManageUserView

app_name = "user"

urlpatterns = [
    path("create/", CreateUserView.as_view(), name="create"),
    path("token/", CreateTokenView.as_view(), name="token"),
    path("me/", ManageUserView.as_view(), name="me"),
]

tasker/lists/models.py
from django.contrib.auth.models import User
from django.db import models

class List(models.Model):
    title = models.CharField(max_length=75)
    user = models.ForeignKey(User,on_delete=models.CASCADE,related_name='lists')
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

class Task(models.Model):
    parent_list = models.ForeignKey(List, on_delete=models.CASCADE, related_name='tasks')
    title = models.CharField(max_length=75)
    completed = models.BooleanField(default=False, blank=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

tasker/lists/api/views.py
from rest_framework import viewsets
from rest_framework.authentication import SessionAuthentication
from rest_framework.permissions import IsAuthenticated
from .serializers import TaskSerializer, ListSerializer
from ..models import Task, List

class ListViewSet(viewsets.ModelViewSet):
    queryset = Task.objects.all()
    serializer_class = ListSerializer
    authentication_classes = [SessionAuthentication]
    permission_classes = [IsAuthenticated]

    def get_queryset(self):
        user = self.request.user
        return List.objects.filter(user=user)

    def create(self, request, *args, **kwargs):
        serializer = ListSerializer(data=request.data)
        if serializer.is_valid():
            serializer.save(user=request.user)
            return Response(serializer.validated_data, status=status.HTTP_201_CREATED)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)

class TaskViewSet(viewsets.ModelViewSet):
    queryset = Task.objects.all()
    serializer_class = TaskSerializer
    authentication_classes = [SessionAuthentication]
    permission_classes = [IsAuthenticated]

    def get_queryset(self):
        user = self.request.user
        return Task.objects.filter(parent_list__user=user)

tasker/lists/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, get_object_or_404

from .models import List

@login_required
def home(request):
    return render(request, 'index.html', {
        'lists': request.user.lists.all()
    })


@login_required
def list_detail(request, list_id):
    user_list = get_object_or_404(List, id=list_id)
    return render(request, 'detail.html', {
        'list': user_list
    })

tasker/lists/templates/lists/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1"/>
    <title>{% block title %} {% endblock %}</title>

    <link href="https://unpkg.com/tailwindcss@^1.0/dist/tailwind.min.css" rel="stylesheet">

    <script src="https://cdn.jsdelivr.net/gh/alpinejs/alpine@v2.x.x/dist/alpine.min.js" defer></script>
    <script src="https://unpkg.com/axios/dist/axios.min.js"></script>
</head>
<body class="bg-gray-100">


    <div class="bg-green-500 py-8 text-center">
        <h1 class="text-gray-100 font-black text-4xl tracking-5">To-Do List App</h1>
        <p class="text-green-800 font-medium font-mono text-sm">Written with Django, Django Rest Framework, TailwindCSS, Alpine.js</p>
    </div>
{% block content %}
{% endblock %}

</body>
</html>

tasker/lists/templates/lists/detail.html
{% extends "base.html" %}

{% block title %}
{{ list.title }} - ToDos
{% endblock %}

{% block content %}

<div class="mx-4 md:mx-32 my-16 bg-white shadow p-8 px-8 rounded-sm">
    <h2 class="text-green-500 font-black text-2xl uppercase text-center">{{ list.title }}’s ToDos</h2>
    <form id="list-form">
        {% csrf_token %}
    </form>
    <div class="flex justify-end mt-4">
        <div class="rounded-md border shadow p-2 flex-1 inline-flex">
            <input class="mr-2 w-5/6" type="text" placeholder="new task">
            <button class="w-1/6 border px-2 py-1 font-mono text-sm bg-green-400 hover:bg-green-500 active:bg-green-700 text-gray-100">Add Task</button>
        </div>
    </div>

    <ul class="mt-4">
        {% for task in list.tasks.all %}
        <li class="bg-gray-100 border border-gray-300 rounded-md shadow-sm p-2 px-4 my-2 flex justify-between font-mono">
            <div class="flex justify-start">
                <button class="mr-2">
                    <svg class="h-5 text-gray-500 hover:text-red-500" fill="none" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewBox="0 0 24 24" stroke="currentColor"><path d="M10 14l2-2m0 0l2-2m-2 2l-2-2m2 2l2 2m7-2a9 9 0 11-18 0 9 9 0 0118 0z"></path></svg>
                </button>
                <p class="text-gray-800">{{ task.title }}</p>
            </div>
            {% if task.completed %}
                <button class="text-green-500 hover:text-gray-500 cursor-pointer">Completed</button>
            {% else %}
                <button class="text-gray-500 hover:text-green-500 cursor-pointer">Not Completed</button>
            {% endif %}

        </li>
        {% endfor %}
    </ul>
</div>

{% endblock %}

tasker/lists/templates/lists/index.html
{% extends "base.html" %}

{% block title %}
To-Do List App
{% endblock %}

{% block content %}

<div class="mx-4 md:mx-32 my-16 bg-white shadow p-8 px-8 rounded-sm">
    <h2 class="text-green-500 font-black text-2xl uppercase text-center">{{ request.user.username }}’s Lists</h2>
    <form id="list-form">
        {% csrf_token %}
      </form>
    <div class="flex justify-end mt-4">
        <div class="rounded-md border shadow p-2 flex-1 inline-flex">
            <input class="mr-2 w-5/6" type="text" placeholder="new list">
            <button class="w-1/6 border px-2 py-1 font-mono text-sm bg-green-400 hover:bg-green-500 active:bg-green-700 text-gray-100">Add List</button>
        </div>
    </div>

    <ul class="mt-4">
        {% for list in lists %}
        <li class="bg-gray-100 border border-gray-300 rounded-md shadow-sm p-2 px-4 my-2 flex justify-between">
            <a href="{% url 'lists:detail' list.id  %}" class="border border-gray-100 text-green-800 font-mono px-2 py-1 hover:text-green-500">{{ list.title }}</a>
            <button class="border px-2 py-1 font-mono text-sm bg-red-400 hover:bg-red-500 text-gray-100">Delete List</button>
        </li>
        {% endfor %}
    </ul>

</div>

{% endblock %}